# Generated by Django 6.0.5 on 2026-06-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
