
services:
    database:
      container_name: db
      image: postgres:18.4-alpine3.23
      env_file:	
        - ./.env
      volumes:
        - postgres_data:/var/lib/postgress/data
	  
    backendend:
      container_name: backend
      build:
        context: .
        dockerfile: ./apps/docker/backend/Dockerfile.bdev
      env_file:
        - ./.env
      volumes:
        - ./apps/backend:/apps/backend
        - static:/apps/backend/productionfiles
      depends_on:
        - db
      ports:
        - 8000:8000
    frontend:
      container_name: frontend
      build:
        context: .
        dockerfile: /apps/docker/frontend/dockerfile.fdev
      ports:
        - 3000:3000
      env_file:
        ./.env
      volumes:
        - ./apps/frontend:/apps/frontend
    nginx:
      container_name: nginx
      build:
        context: .
        dockerfile: ./apps/docker/nginx/Dockerfile
      ports:
        - 80:80
      volumes:
        - static:/apps/backend/productionfiles
        - ./apps/docker/nginx/nginx.dev.config:/etc/nginx/conf.d/nginx.conf
    
volumes:
  static:
  postgres_data: