# Generated by Django 6.0.5 on 2026-06-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_commands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roleID',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
