FROM python:3.15.0b1-slim-bookworm

WORKDIR /apps/backend

COPY ./apps/backend .

RUN python3 -m venv /opt/venv && \
/opt/venv/bin/pip install --upgrade pip && \
/opt/venv/bin/pip install requirement.txt

RUN /opt/venv/bin/python manage.py collecstatic

CMD [ "/opt/venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]

